services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./bookmarks:/code
      - ./bookmarks/db.sqlite3:/code/db.sqlite3
    env_file:
      - .env
    networks:
      - CP-network
    init: true
    restart: always

volumes:
  django_data:

networks:
  CP-network:
    name: CP-network
